config/routes.rb
Smugglerscovebuddy::Application.routes.draw do
  root to: 'tiki#new'
  post 'tiki/party'

  resources :cocktails
  resources :ingredients
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_and_belongs_to_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_and_belongs_to_many :cocktails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cocktail }
      else
        format.html { render action: 'new' }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, {ingredient_ids: []})
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
  end

  def create
    @ingredient = Ingredient.create!(ingredient_params)
  end

  def index
    @ingredients = Ingredient.all
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/tiki_controller.rb
class TikiController < ActionController::Base
  def new
  end

  def party
    @cocktails = Cocktail.where()
    puts tiki_params
  end

  private

  def tiki_params
    params.require(:tiki).permit({ingredient_ids: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
      <% @cocktail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing cocktail</h1>

<form action="<%= cocktail_url(@cocktail.id) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="text" name="cocktail[name]" value="<%= @cocktail.name %>">

  <%= collection_check_boxes :cocktail, :ingredient_ids, Ingredient.all, :id, :name %>

  <input type="submit" value="Edit Cocktail">
</form>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/index.html.erb
<h1>Listing cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<form action="<%= cocktails_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="cocktail[name]">

  <%= collection_check_boxes :cocktail, :ingredient_ids, Ingredient.all, :id, :name %>

  <input type="submit" value="Create Cocktail">
</form>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
  <ul>
  <% @cocktail.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

app/views/ingredients/create.html.erb
<h1>Ingredients#create</h1>
<p>Find me in app/views/ingredients/create.html.erb</p>

<p><%= @ingredient.inspect %></p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

<ul>

<% @ingredients.each do |ingredient| %>
  <li><%= ingredient.name %></li>
<% end %>

</ul>

app/views/ingredients/new.html.erb
<h1>Ingredients#new</h1>
<p>Find me in app/views/ingredients/new.html.erb</p>

<form action="<%= ingredients_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="ingredient[name]">

  <input type="submit" value="Create Ingredient">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smugglerscovebuddy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tiki/new.html.erb
<h1>Tiki Time</h1>

<form action="/tiki/party" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <%= collection_check_boxes :tiki, :ingredient_ids, Ingredient.all, :id, :name %>

  <input type="submit" value="Submit">
</form>

app/views/tiki/party.html.erb
<h1>Listing cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Edit', edit_cocktail_path(cocktail) %></td>
        <td><%= link_to 'Destroy', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>